Make "Bad %if condition" error message more informative
The original message like e.g.:

error: /root/rpmbuild/SPECS/iftest.spec:8: bad %if condition

is changed to

error: /data/SPECS/iftest.spec:39: Bad %if condition:  nonsense-3