rpmrc: Fix missing declaration of personality() on sparc*-linux
Fixes the following link failure on sparc*-linux which occurs due to
name mangling of the personality() symbol name when mixing C and C++:

/usr/bin/sparc64-linux-gnu-ld.bfd: ../lib/librpm.so.10.8.0: undefined reference to `personality(unsigned long)'
collect2: error: ld returned 1 exit status

To fix the failure, remove the external declaration of personality()
and include <sys/personality.h> instead which properly wrap C symbols
with 'extern "C"' to prevent symbol name mangling.