Bring RPM_MASK_RETURN_TYPE in to the signed int range
Set to 0xffff0000 (or 4294901760), I was getting:

     error: ISO C restricts enumerator values to range of 'int' (4294901760 is too large) [-Werror,-Wpedantic]

This happened not when building rpm itself, but when building
rpminspect which links with librpm and uses rpm's headers.  The system
in question was FreeBSD 13.1 which has clang 13.0.0.

It is a corner case, but I like testing things on non-Linux platforms
as often as I can to find errors like this.

With this change, the rpm test suite passes for me.

Signed-off-by: David Cantrell <dcantrell@redhat.com>
(cherry picked from commit 8310b34a38b419b0ae6a7669805754f11e472c1c)