Ensure dependency matches from rpmdb are actually in range
Given the following situation (following --nodeps):
* package foo is installed that Requires: bar = 1.0
* package baz is installed that Provides: bar = 2.0
* nothing on the system provides bar = 1.0

Previously, an attempt to remove baz would result in:
error: Failed dependencies:
        bar = 1.0 is needed by (installed) foo-1.0-1.x86_64

...which is quite clearly wrong, foo was never the provider in the first
place so it shouldn't come up at all. This is a truly ancient bug, quite
possibly been there all along.

Problem is, we were only looking up rpmdb matches by name. Adjust callers
to pass in an actual dependency set where it exists (everything but
file dependencies in practise) and only verify dependencies for overlapped
dependency ranges. Extend our unsatisfied dependency test-case to cover
this corner as well.