Fix delete_key_compat() friend definition
Commit e360ca338e5215a2015fef6ed843cfefd8463f2e mistakenly defined the
function as static while also declaring it as a friend function in the
keystore header file. While GCC didn't seem to mind, Clang failed with:

    error: static declaration of 'delete_key_compat' follows non-static
    declaration

And rightfully so. We just didn't notice since most of us build with GCC
(including the CI), oops.

Fix by dropping the static keyword. This is fine because access control
and visibility is handled by C++ here (since it's a friend function, not
a standalone one), and the keystore API isn't public anyway.

Fixes: #4070
(cherry picked from commit 9610233289717f82b5f633858b858ca7054c18be)