Improve expression error messages
The error messages created by the parser have been truly lame and with
zero context. No to mention typos such as multiple instances of "suported".
Add an error reporting helper which uses the parse state to report not
only the expression where the error occurred but also pinpoints the exact
character in the cases where we easily can, eg:

	error: syntax error in expression:  (1 && 0)) + 5
	error:                                      ^

(cherry picked from commit 4fc0370c56f301c228d592a35b52b76023479953)