Exit from mktree on failure
Right now, if the podman image fails to build or rpm fails to
build/install, we happily continue and run the test-suite, only to
eventually fail with some cryptic error, such as:

    error: cannot find rpm

Not too helpful, indeed.  Instead, just fail the whole tree preparation
process if we encounter an error.

Fix the return code of unshared() so that we don't fail on that, though.
Also, when building the RPM layer, use a proper cleanup trap instead of
ignoring SIGINT since a failing make_install() can now terminate the
script.

Fixes: #2667