Fix an "expected expression" error
In C, a label should be followed by a statement, not a declaration. The
`setmeta` label in `lib/fsm.c` violated this, and led to a build error
with an error message like the one below:

```
  fsm.c:1019:6: error: expected expression
              int mayopen = S_ISREG(fp->sb.st_mode) || S_ISDIR(fp->sb.st_mode);
              ^
  fsm.c:1020:29: error: use of undeclared identifier 'mayopen'
              if (!rc && fd == -1 && mayopen) {
                                     ^
  2 errors generated.
```

This could be fixed by introducing an empty statement (a single semi-
colon). That is a statement.

Signed-off-by: Ruoyu Zhong <zhongruoyu@outlook.com>