Enable updates in the test-suite image
Update repositories have been disabled in the test-suite image to
have a stable base against which tests run, but this is based on the
false assumption that the base image (currently fedora:44) never changes.
It does get updated from time to time, and then we end up *downgrading* a
whole bunch of stuff when we install our own dependencies with updates
disable.  So we end up with this bizarre mixture that nobody is expected
to use or test, and if it breaks we can't even complain to anybody because
this mixture is just boinkers.

The most recent breakage is test-suite blowing up with messages like:

    ImportError: /usr/local/lib64/librpm.so.10: undefined symbol: _ZNSt8__format15__do_vformat_toIcLj1EEENS_10_Sink_iterIT_EES3_St17basic_string_viewIS2_St11char_traitsIS2_EERSt20basic_format_contextIS3_S2_E, version GLIBCXX_3.4.35

The only surprise here is that breakages like these haven't been more
common.

While at it, drop the Semaphore CI remnant as well. We haven't been
there for years.