Fix misleading error message when missing TTY (#355)
$ rpm -e mlocate </dev/null
error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Inappropriate ioctl for device)

Save and restore errno around isatty() since that's not the interesting
thing here.