Make python examples run with python 3, the print commands.
Addressing things like
    print s.prep()
          ^
SyntaxError: invalid syntax

(cherry picked from commit 66b5a7750afc46c41f2272a6774f82b6448951d8)