Set RPM_PLUGINDIR in top level CMakeLists.txt
We have in macros.in:
  %__plugindir          @RPM_PLUGINDIR@

This means, if RPM_PLUGINDIR is not set, %__plugindir will be empty.
This in turn results in error message when running 'dnf'.

e.g.,
dnf --help >/dev/null
error: /usr/lib64/rpm/macros: line 1183: Macro %__plugindir has empty body
error: /usr/lib64/rpm/macros: line 1183: Macro %__plugindir has empty body

So we should move this directory setting into the top level CMakeLists.txt.

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
(cherry picked from commit cae8ef521690ef07aa5664da2575e37126ee52cc)