rpm.spec's .prep seems to be an attribute.
Addressing
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    print(s.prep())
TypeError: 'str' object is not callable

(cherry picked from commit 5b9053e36e627685b6fcad72ad3655a07ceecac8)