tests: Do not use interactive mode for mktree.podman "make check"
This causes execution to choke in CI environments like GitHub Actions
that do not provide a tty with errors like the following:

    sudo ./mktree.docker check
    shell: /usr/bin/bash -e {0}
  the input device is not a TTY
  Error: Process completed with exit code 1.

We want to avoid this and actually have the CI run properly.