rpm/transaction: move from __future__ to the top
*** Error compiling '/builddir/build/BUILDROOT/rpm-4.13.0_alpha-239g190fa42.fc24.x86_64/usr/lib64/python3.5/site-packages/rpm/transaction.py'...
  File "/usr/lib64/python3.5/transaction.py", line 9
SyntaxError: from __future__ imports must occur at the beginning of the file

Signed-off-by: Igor Gnatenko <ignatenko@redhat.com>