Prevent automatic garbage collection in git based %autosetup macros
The garbage collection happens in background, based on heuristic.
This means that sometimes, when subsequent commands run,
some files might disappear in the middle of an action.

For example, when a find is used in %prep:

    + /usr/bin/git commit -m ... --author 'rpm-build <rpm-build>'
    Auto packing the repository in background for optimum performance.
    See "git help gc" for manual housekeeping.
    ...
    + find ...
    find: './.git/objects/47': No such file or directory
    find: './.git/objects/46': No such file or directory
    find: './.git/objects/49': No such file or directory
    find: './.git/objects/4d': No such file or directory
    error: Bad exit status from /var/tmp/rpm-tmp.xxxxxx (%prep)