python: Use Py_hash_t instead of long in hdr_hash
Fixes
python/header-py.c:744:2: error: incompatible function pointer types initializing 'hashfunc' (aka 'int (*)(struct _object *)') with an expression of type 'long (PyObject *)' (aka 'long (struct _object *)') [-Wincompatible-function-pointer-types]
|         hdr_hash,                       /* tp_hash */
|         ^~~~~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>