Remove RPM_MASK_RETURN_TYPE from rpmTagReturnType_e; make it a macro
RPM_MASK_RETURN_TYPE is 0xffff0000 which is UINT_MAX.  Per ISO C,
enumerator values must be in the signed int range.  gcc is more
forgiving with this than certain versions of clang and if you are on a
random system, such as FreeBSD 13.1 with clang 13.0.0, you will get
this error when trying to compile software that links with librpm and
uses the rpm headers:

    error: ISO C restricts enumerator values to range of 'int' (4294901760 is too large) [-Werror,-Wpedantic]

Similar to the other enums in rpmtag.h, RPM_MASK_RETURN_TYPE is not
actually a value used from the enum, so take it out of the enum and
make it a macro.

Signed-off-by: David Cantrell <dcantrell@redhat.com>
(cherry picked from commit 3cec5f81cd202946c2ea033c966919262daacb1e)