Return -1 from fdSize() for non-regular files
I noticed that importing a key from a pipe did not work:

    $ cat /tmp/key | rpmkeys --import -
    error: -: import read failed(0).

While importing from a regular file on stdin worked:

    $ < /tmp/key rpmkeys --import -

The cause was fdSize() returning 0 for a pipe descriptor.
rpmcliImportPubkeys() calls rpmioSlurp() which calls fdSize() like
this:

    size = fdSize(fd);
    blen = (size >= 0 ? size : blenmax);
    if (blen) {
    	/* read from the descriptor */
    }

As a result, rpmioSlurp() concluded that the "file" was empty and
rpmcliImportPubkeys() reported an error:

    iorc = rpmioSlurp(fn, &buf, &blen);
    if (iorc || buf == NULL || blen < 64) {
        rpmlog(RPMLOG_ERR, _("%s: import read failed(%d).\n"), fn, iorc);

This patch changes fdSize() to return an error for non-regular files.
This is in line with fstat(3) manual:

       st_size
              This field gives the size of the file (if it is
              a regular file or a symbolic link)  in bytes.  The size
              of a symbolic link is the length of the pathname it
              contains, without a terminating null byte.

Returning an error on unsupported descriptors was pretty common before
commit 852398f8c6dcb4ad5ed0310e49e7d342a262be91
("Lose unnecessary url type checking from fdSize()").