rpmio/lposix.cc: remove LUALIB_API in luaopen_posix() definition
In file rpmio/lposix.cc the luaopen_posix() function is defined
with LUALIB_API, but in the header it doesn't have it.

This can produce some problems:

WARN /home/build/rpmio/lposix.cc:874:16: error: conflicting declaration of 'int luaopen_posix(lua_State*)' with 'C' linkage
WARN   874 | LUALIB_API int luaopen_posix (lua_State *L)
WARN       |                ^~~~~~~~~~~
WARN In file included from /home/build/rpmio/lposix.cc:38:
WARN /home/build/rpmio/lposix.hh:11:5: note: previous declaration with 'C++' linkage
WARN    11 | int luaopen_posix (lua_State *L);
WARN       |     ^~~~~~~~~~~

This symbol LUALIB_API is not required, and is an ancient leftover.

Signed-off-by: Arturo Borrero Gonzalez <arturo.borrero@chainguard.dev>
(cherry picked from commit 266bdeeaf77422b408640c65de00b696fb710e2d)