rpmfc: '/bin/sh failed: 100' should go to DEBUG
When getOutputFrom() is set to fail with non-zero return code, it should
not dump non user-friendly (no context, no user return code) message
into a terminal.

error: /bin/sh failed: 100

References: https://github.com/rpm-software-management/rpm/issues/728
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>