Make "Bad %if condition" error message more general and  informative
The original message like e.g.:

error: /data/rpmbuild/SPECS/iftest.spec:8: bad %if condition

is changed to

error: /data/rpmbuild/SPECS/iftest.spec:8: Bad %if condition:  nonsense-3

Preparation for %elif.